spring:
  datasource:
    url: jdbc:sqlserver://112.74.13.227:63008;DatabaseName=mis
    username: ERP
    password: qiyang@2013
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true

# 日志
logback:
  fileLevel: info                          # 文本日志级别
  consoleLevel: info                        # 控制台日志级别
  filePath: ./logs/webapps/mis-dev         # 日志文件存储路径  tomcat/bin 目录下

server:
  port: 8090
