spring:
  datasource:
    url: jdbc:sqlserver://112.74.13.227:63008;DatabaseName=mis
    username: ERP
    password: qiyang@2013
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true

# 日志
logback:
  fileLevel: info                          # 文本日志级别
  consoleLevel: info                        # 控制台日志级别
  filePath: ./logs/webapps/mis-dev         # 日志文件存储路径  tomcat/bin 目录下

server:
  port: 8090

param:
  login:
    token:
      expired: 3600       # 登录token有效时长, 单位: 秒
      refreshExpired: 604800 # 刷新 token 有效时长, 单位: 秒
      grace: 5                # 宽限时间 单位: 秒
